config/routes.rb
Puntificate::Application.routes.draw do

  
  root :to => 'challenges#index'

  devise_for :users

  resources :challenges do
    post :upvote
    post :downvote

    get :upvote
    get :downvote
    resources :responses do
      post :upvote
      post :downvote

      get :upvote
      get :downvote
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Puntificate" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>    
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Puntificate", root_path, :class => 'brand' %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Challenges", challenges_url  %></li>
            </ul>
            <ul class="nav pull-right">                                                                             
              <% if user_signed_in? %>
                      <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                          <%= "#{current_user.name} (#{current_user.score})" %>
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                        </ul>                        
                      </li>
                      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              <% else %>                                              
                      <li><%= link_to "Sign In", new_user_session_path %></li>
                      <li><%= link_to "Register",     new_user_registration_path %></li>
              <% end %>                                       
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container" style="padding-top:60px">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield(:javascript) %>
  </body>
</html>